### ISSUE TITLE
Login Page Does Not Open

### ISSUE THREAD

**Issue by sixshooterz** [nextcloud/univention-app#1]
After fresh install the login page does not open.  For some reason, the link on the UCS user page directs to HTTP instead of HTTPS.  Correcting the url in the address bar opens the page as it should.  Unfortunately there's not a registry entry to fix this, at least that I could see. Any help would be greatly appreciated!

EDIT:  Hovering over the Nextcloud link on the UCS page shows that it should connect to the SSL-enabled site, however, clicking on the link takes the user to the HTTP site.

**Comment by MiGrandjean** [comment]
AFAIK this has been fixed today in the UCS App Center package: https://errata.software-univention.de/ucs/4.1/406.html 
New installations should be fine. Existing installations might need to run `ucr set ucs/web/overview/entries/service/nextcloud/port_http='' ucs/web/overview/entries/service/nextcloud/port_https='443'` on the UCS host.
