### ISSUE TITLE
Nextcloud app doesn't support deleting or renaming groups

### ISSUE THREAD

**Issue by ngulden** [nextcloud/univention-app#104]
Changing the name of a group or deleting it, isn't reflected in Nextcloud.

Furthermore, when a group doesn't exist in LDAP anymore, but is still in Nextcloud, it cannot be deleted there anymore.

Taken from https://forge.univention.org/bugzilla/show_bug.cgi?id=47178. 

@blizzz : Is this still the case?

**Comment by blizzz** [comment]
Deleted groups should not appear anymore (latest when cache was invalidated). But it is true that there is no clean up process for the remnants at the moment.

Support for group display names comes with Nextcloud 17.

**Comment by blizzz** [comment]
group display names are available meanwhile. Cleaning up LDAP group remnants is not, but this has to be added to https://github.com/nextcloud/server
