### ISSUE TITLE
change cron to 5 min with nc17

### ISSUE THREAD

**Issue by Lebernd** [nextcloud/univention-app#110]
https://github.com/nextcloud/univention-app/blob/580fd1e13bc3cf2b941d4ad68e9a0c22ba588f98/setup#L160

the line should reflect the new docs: https://docs.nextcloud.com/server/17/admin_manual/configuration_server/background_jobs_configuration.html

so should be:
`echo "*/5 * * * * www-data    php -f /var/www/html/cron.php" > /etc/cron.d/nextcloud`

**Comment by blizzz** [comment]
@Lebernd  yes, reasonable. do you mind open a pull request? :)

**Comment by blizzz** [comment]
fixed by #111
