### ISSUE TITLE
well-known problem is back after fresh install 17.0.2-0

### ISSUE THREAD

**Issue by smooth-baking-powder** [nextcloud/univention-app#113]
Hi,

today i installed a fresh Univention Memberserver for Nextcloud 17.0.2-0.

Yesterday i uninstalled an backup all Data of 16.0.6-0. 
After install and config i let all data sync back in the cloud.

Now i show in the webgui, i have the well-known warning again.
My davX on android cant connect with the Server. The normal Nextcloud app is connected with the Server.

Here is my System detail:
https://cloud.c-lab.one/nextcloud/s/JEy9Cso7FqgJj9P
vEe7opdNdTjic53gbqE9

at the moment i use the apache2 workaround:
Redirect 301 /.well-known/carddav /nextcloud/remote.php/dav
Redirect 301 /.well-known/caldav /nextcloud/remote.php/dav

I hope you can help me to solve it and its not a version problem :/

Best Regards

**Comment by blizzz** [comment]
Please check the host configuration, we cannot do anything reliably from the app

> **Not able to resolve "/.well-known/caldav|carddav"**
> Discovery of addressbook and calendar services can be made easier for such clients, by providing well-known URLs that redirect to the actual location of that service. This check tests whether the top-level domain has the given URLs present. Again, to resolve this, the web server configuration of the host needs to be adjusted, <a href="https://docs.nextcloud.com/server/17/admin_manual/issues/general_troubleshooting.html#service-discovery">according to this documentation</a>.
It is only possible to link to one service provider on a domain. Having the URLs present is not crucial for a working Nextcloud setup, but improves the convenience for some end users.
The check was introduced within the Nextcloud 13 series. Thus in the earlier version the hint was not shown.
