### ISSUE TITLE
Cron dont work on 17.0.2-0

### ISSUE THREAD

**Issue by smooth-baking-powder** [nextcloud/univention-app#114]
Hi,

my problem is on 17.0.2-0, the cron dont work. On the Weekend i installed the new Version of Nextcloud on a fresh installed Memberserver. At the Moment i have over 20 hours no cron, after i opened the cron.php manually.
I tested it with 3 memberserver and dc master in test area vm on my workstation.
On Nextcloud Memberserver updated from 16.x.x-x all is fine.

Test DC Master over 16 Minutes
![2020-02-05 18_27_55-Window](https://user-images.githubusercontent.com/21257329/73866513-46716000-4845-11ea-8576-653e07980ccb.jpg)

Cron is running in container and settings are on 15 minutes

reproduce:
install univention memberserver
install nextcloud app
restart server
show in settings

Symptome:
Cron dont refresh after 15 minutes (after look in crontab and ticket https://github.com/nextcloud/univention-app/issues/110)

**Comment by blizzz** [comment]
Do you have the maps app enabled? https://github.com/nextcloud/maps/issues/282

**Comment by blizzz** [comment]
mh, to answer myself, probably not. Is the entry in  the crontab present? Did you check the logs?

**Comment by smooth-baking-powder** [comment]
For clarity:
Server 1 is productive and updated from 16.x.x-x
Server 2 is a new installed server in Domain of Server 1
Server 3 is new master DC Server in a VM on my Workstation

Maps:
(Server 2) Maps was enabled, i disabled it, cause i got other errors. I found the Solution here:
https://help.nextcloud.com/t/cron-php-call-to-a-member-function-getuserfolder-on-null/69899/6
On This Server Cron work now!

(Server 3) On Test Servers Maps didnt installed, Cron dont work.
(Server 1) On my updated Server Maps is installed and cron work fine, no errors.
(its a little bit crazy i think)

Other:
In the Logs i didnt find any cron on Test Server (Server 2). On updated Server (Server 1) the cron is in the log that i used for search.

So the Problem is solved i think. Server 2 is working fine. I will check the Test server, but its no priority. I will write here again, if i found the problem.
