### ISSUE TITLE
Keep app settings over updates

### ISSUE THREAD

**Issue by ofriedri** [nextcloud/univention-app#124]
If I restrict the visibility of apps to several user groups (e.g. "Domain Admins") and update the nextcloud App via the app center, then the app visibility is reset so that every user can see the apps again.

AFAIK are the visibility settings app-specific and need therefore be kept between updates.

**Comment by blizzz** [comment]
This should not change as the information is kept in the database. Know I know it is some time since the report :see_no_evil: please re-open if it still keeps happening.
