### ISSUE TITLE
Roadmap regarding nextcloud 19

### ISSUE THREAD

**Issue by Fuseteam** [nextcloud/univention-app#126]
i would like to ask when the ucs app is planned to be updated to 19 [according to some people](https://github.com/nextcloud/nextcloud-snap/issues/1342#issuecomment-639422089) 19 is already released in production

**Comment by blizzz** [comment]
Not before 19.0.1, as we have a mixed audience on this platform. Just as we did with the releases in the past :)

**Comment by Fuseteam** [comment]
@blizzz thanks for the swift response :)
any place i can follow when 19.0.1 is released?

**Comment by blizzz** [comment]
UCS app center should inform you, when it will be available on UCS. 

Generally in Nextcloud, we have the release schedule: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by Fuseteam** [comment]
@blizzz thank you :+1:
