### ISSUE TITLE
OS X 10.14+ needs better redirects for .well-known DAVs

### ISSUE THREAD

**Issue by andipilz** [nextcloud/univention-app#132]
When using NextCloud as DAV backend with UCS 4.4, OS X is not able to reliably use the function of server detection using ".well-known" due to improper redirects for:
- /.well-known/caldav
- /.well-known/carddav

This can be handled with a proper redirect on (in my case) FQDN level adding in the file /etc/apache2/sites-enabled/default-ssl.conf or the respective template.

Below:

   ProxyPass /nextcloud http://127.0.0.1:40000/nextcloud retry=0
   ProxyPassReverse /nextcloud http://127.0.0.1:40000/nextcloud

The redirects to the FQDN to be included are:

   Redirect 301 /.well-known/carddav https://<fqdn>/nextcloud/remote.php/dav
   Redirect 301 /.well-known/caldav https://<fqdn>/nextcloud/remote.php/dav

Additionally it is necessary to have NextCloud and UCS-System on HTTPS as mandatory!!! (Might be enough to mention in handbook.)

This follows the hints in the documentation of NextCloud relating to services discovery: https://docs.nextcloud.com/server/18/admin_manual/issues/general_troubleshooting.html#service-discovery
in case, that - as with UCS - the NextCloud instance is address via /nextcloud.

See also: https://forge.univention.org/bugzilla/show_bug.cgi?id=52008 (closed)

**Comment by Fuseteam** [comment]
this is not just a macos bug btw, it much more general, this breaks caldav and carddav syncing. I do not see anything in the app itself that could solve this.  i have edited `/etc/apache2/sites-enabled/default-ssl.conf` but that doesn't seem persistent

**Comment by blizzz** [comment]
There is a post_install note, let me quote:

> Discovery of addressbook and calendar services can be made easier for such clients, by providing well-known URLs that redirect to the actual location of that service. This check tests whether the top-level domain has the given URLs present. Again, to resolve this, the web server configuration of the host needs to be adjusted, <a href="https://docs.nextcloud.com/server/20/admin_manual/issues/general_troubleshooting.html#service-discovery">according to this documentation</a>

> It is only possible to link to one service provider on a domain. Having the URLs present is not crucial for a working Nextcloud setup, but improves the convenience for some end users.

The app cannot (for good reason) change the configuration of the reverse proxy on the host.

**Comment by Fuseteam** [comment]
@blizzz maybe leave a comment on the linked univention bugzilla bug tracker that this needs to be solved in univention?
as this leaves nextcloud saying that is it insecure and it **does** make nextcloud less usefull considering nextcloud hub is promoted to be able to sync more than just files
![2021-05-05-142118_1246x155_scrot](https://user-images.githubusercontent.com/10421851/117182862-41cf8a80-adad-11eb-938b-e85534f86bcc.png)

**Comment by Fuseteam** [comment]
oh my goodness the solution was just overlooked because we tend to skip the comments when we searching for what we need
this is what comments in `/etc/apache2/sites-enabled/defaul.ssl.conf` actually says:
```
# Warning: This file is auto-generated and might be overwritten by
#          univention-config-registry.
#          Please edit the following file(s) instead:
# Warnung: Diese Datei wurde automatisch generiert und kann durch
#          univention-config-registry ueberschrieben werden.
#          Bitte bearbeiten Sie an Stelle dessen die folgende(n) Datei(en):
#
#       /etc/univention/templates/files/etc/apache2/sites-available/ssl.d/00start
#       /etc/univention/templates/files/etc/apache2/sites-available/ssl.d/10hsts
#       /etc/univention/templates/files/etc/apache2/sites-available/ssl.d/10univention-appcenter
#       /etc/univention/templates/files/etc/apache2/sites-available/ssl.d/99end
#
```
the solution is adding the following two lines in ` /etc/univention/templates/files/etc/apache2/sites-available/ssl.d/99end` and running ucr for example by running `ucr set apache2/hsts=yes` to set hsts, another property that has to be set on the host
```
Redirect 301 /.well-known/carddav https:///nextcloud/remote.php/dav
Redirect 301 /.well-known/caldav https:///nextcloud/remote.php/dav
```
