### ISSUE TITLE
smbclient missing

### ISSUE THREAD

**Issue by IT-Hebk** [nextcloud/univention-app#133]
I think something went wrong creating the new 19.03 docker image. The smbclient is missing

see: https://help.univention.com/t/nextcloud-19-0-3-smbclient-missing/16128/2

**Comment by staeglis** [comment]
I've created a pull request regarding this issue:
https://github.com/nextcloud/univention-app/pull/134

**Comment by blizzz** [comment]
As workaround please see https://github.com/nextcloud/univention-app/pull/134#issuecomment-706333070
