### ISSUE TITLE
Crontab entry lost on update

### ISSUE THREAD

**Issue by hnordmeyer** [nextcloud/univention-app#14]
Updated from Nextcloud 11.0.1 to 11.0.2 via univention app center and the crontab entry within the docker image got lost.

At least, it doesn't exist YET - I found out by reading the nextcloud message saying that last cron execution was 20 hours ago. Cannot say whether or not it existed before, but crons had been executed.

After creating /etc/conf.d/nextcloud manually, all works fine now.

**Comment by blizzz** [comment]
@hnordmeyer thank you for reporting this! Indeed it is a bug. We configure cron only on install, but since the config is located on a not permanent dir, it will get lost after update.

**Comment by Fuseteam** [comment]
this seems to still be an issue on 21, tho i have a feeling is related to how the [official documentation](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html) made us set up cron.

**Comment by blizzz** [comment]
The entry should be created on setup as /etc/cron.d/nextcloud

**Comment by Fuseteam** [comment]
That seems to exist when we create the cron tab via univention-app shell nextcloud. Those changes appears to get lost when the docker image gets updated tho

**Comment by blizzz** [comment]
I cannot reproduce this, the file exists after several upgrades.

**Comment by Fuseteam** [comment]
Hmm guess we'll need to take closer look at what is happening, thanks for testing

**Comment by Fuseteam** [comment]
We looked into it. For now, it appears that updates to a cronjob through crontab are not reflected in the file
