### ISSUE TITLE
internal server error on update 20.0.8

### ISSUE THREAD

**Issue by Lebernd** [nextcloud/univention-app#140]
There is already solution to avoid this in the univention forum: 
https://help.univention.com/t/nextcloud-login-problem-after-upgrade-from-20-0-2-to-20-0-8/17554

But this will disable talk/spreed.

I have the following log-message:
{"reqId":"5viCGhVgA03SaqZ6pMlH","level":4,"time":"2021-03-24T18:29:15+00:00","remoteAddr":"MYIP","user":"MYUSER","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/MYUSER/","message":{"Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"Doctrine\\DBAL\\Exception\\TableNotFoundException: An exception occurred while executing 'SELECT \"r\".*, \"p\".* FROM \"oc_talk_rooms\" \"r\" LEFT JOIN \"oc_talk_participants\" \"p\" ON (\"p\".\"user_id\" = ?) AND (\"p\".\"room_id\" = \"r\".\"id\") WHERE \"p\".\"user_id\" IS NOT NULL' with params [\"MYUSER\"]:\n\nSQLSTATE[42P01]: Undefined table: 7 FEHLER:  Relation »oc_talk_participants« existiert nicht\nLINE 1: ...T \"r\".*, \"p\".* FROM \"oc_talk_rooms\" \"r\" LEFT JOIN \"oc_talk_p...\n                                                             ^","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":192,"function":"check","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->"},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":144,"function":"check","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":458,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/html/remote.php","line":167,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/apps/dav/lib/Connector/Sabre/Auth.php","Line":163,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh) mirall/3.1.3git (build 4850) (Nextcloud)","version":"20.0.8.1","id":"605b8518bf583"}

**Comment by blizzz** [comment]
I didn't not come across this issue when testing. Which version of Talk is installed?

**Comment by blizzz** [comment]
For reference: https://github.com/nextcloud/spreed/issues/5324#issuecomment-791398470

**Comment by Lebernd** [comment]
Talk 	10.0.6

**Comment by Lebernd** [comment]
Ok, thank you for the reference. The update to 10.1.3 is working with `wget` and some tar-commands in the container and I can enable talk then.
