### ISSUE TITLE
[question] upgrade to nextcloud 21

### ISSUE THREAD

**Issue by Fuseteam** [nextcloud/univention-app#142]
we are having some latency issues with nextcloud 20, but I've heard nextcloud 21 will improve performance greatly.
are there plans to upgrade to nextcloud 21?

**Comment by blizzz** [comment]
possibly with 21.0.2, no promises, but if all goes well that should be it.

**Comment by Fuseteam** [comment]
sounds good thanks for the quick response

**Comment by Fuseteam** [comment]
thanks for the upgrade, we'll be updating to it this week i think :+1:
