### ISSUE TITLE
Question: how do you register the custom udm-attributes

### ISSUE THREAD

**Issue by theoneandonly-vector** [nextcloud/univention-app#155]
I don't really find where/how they are registered (it's not in the official docs), but you seem to do this using this file:
https://github.com/nextcloud/univention-app/blob/master/attributes

**Comment by blizzz** [comment]
that's correct, the change was done with PR https://github.com/nextcloud/univention-app/pull/152

The documentation should be https://wiki.univention.de/index.php/Integration_with_UCS/Attributes

If you have follow up questions on this matter, best direct them at univention and/or their forum https://help.univention.com/

**Comment by theoneandonly-vector** [comment]
> that's correct, the change was done with PR #152
> 
> The documentation should be https://wiki.univention.de/index.php/Integration_with_UCS/Attributes
> 
> If you have follow up questions on this matter, best direct them at univention and/or their forum https://help.univention.com/

hey there I'm sorry to ask again.. because it's not really documented, at least not so far that I get how to do this manually.
maybe you can tell me and I will update it on https://help.univention.com/ (I already asked there)

when I have my .attributes -file. how do I install / uninstall it manually?

**Comment by blizzz** [comment]
> when I have my .attributes -file. how do I install / uninstall it manually?

I upload them using univention-appcenter-control, you can see it in the Makefile: https://github.com/nextcloud/univention-app/blob/master/Makefile#L40-L62
