### ISSUE TITLE
Update to Nextcloud 22/23

### ISSUE THREAD

**Issue by patti2** [nextcloud/univention-app#156]
According to [the Nextcloud documentation](https://docs.nextcloud.com/server/latest/admin_manual/release_schedule.html), version 21 has reached EOL as of last month.

Is there an ETA for upgrading this Univention App?
If it involves more work than bumping up the version number and publishing the result, I'm sure many users would like to help.

**Comment by r100gs** [comment]
It would be very nice

**Comment by Mornsgrans** [comment]
Any news?
Please note:
It is not possible to update Nexcloud on UCS server within Nextcloud. So an adapted version in Univention app-store is needed for UCS 4.x and 5.x.

**Comment by blizzz** [comment]
releases are published meanwhile, also 23.0.5 is on its way
