### ISSUE TITLE
aptitude is used but is not a dependency

### ISSUE THREAD

**Issue by MiGrandjean** [nextcloud/univention-app#16]
The `inst.sh` uses:

```
NC_MEMBER_OF=`aptitude search univention-ldap-overlay-memberof | grep "^i" -c`
```

but aptitude is not installed by default anymore on new UCS 4.2 installations. This results in:

`/usr/lib/univention-install/50nextcloud.inst: Line 83: aptitude: Command not found.`

So `aptitude` should either be a hard dependency or `inst.sh` should use something else (e.g. `dpkg -l aptitude` or `dpkg-query -W -f='${Status}\n' aptitude`)

**Comment by blizzz** [comment]
Thanks for the report and hinting at the alternatives. ``dpkg-query -W -f='${Status}\n' univention-ldap-overlay-memberof | grep Installed | grep "^i" -c`` would be  my favorite then.
