### ISSUE TITLE
After upgrade to latest version

### ISSUE THREAD

**Issue by CrisCard0so** [nextcloud/univention-app#160]
Univention-app shell does not work or other similar command related to univention-app

<img width="926" alt="Screen Shot 2022-04-25 at 11 19 57" src="https://user-images.githubusercontent.com/88008848/165150010-47681a5e-e661-4531-a4d2-43a905022418.png">

**Comment by Lebernd** [comment]
https://help.univention.com/ 
will probably be a better place to look for help regarding this issue.

**Comment by blizzz** [comment]
> https://help.univention.com/ will probably be a better place to look for help regarding this issue.

Exactly, this is unrelated to Nextcloud. Closing here.
