### ISSUE TITLE
HEIC HEIF support

### ISSUE THREAD

**Issue by Byter3** [nextcloud/univention-app#165]
Currently there is no support for HEIC/HEIF files from imageMagick inside the nextcloud container. Could you recompile ImageMagick for the next upgrade to support HEIC/HEIF files as well? Thank you!

**Comment by blizzz** [comment]
This should be provided when upgrading the base container image to ubuntu 22.04. So far we refrain doing so as some important apps have not reached PHP 8.1 compatibility.

**Comment by Byter3** [comment]
I see. Good to know, that you are aware of this.
Also quick question. Can I just upgrade the imageMagick inside the container, for temporary messure  wothout breaking anything? (I know it's gonna be wiped with an upgrade)

**Comment by blizzz** [comment]
> I see. Good to know, that you are aware of this. Also quick question. Can I just upgrade the imageMagick inside the container, for temporary messure wothout breaking anything? (I know it's gonna be wiped with an upgrade)

At your own risk of course, but it should work. You might need to stop and restart apache2 (`/usr/sbin/apache2ctl -D FOREGROUND`, check the entrypoint script) if it is not being picked up.

**Comment by Byter3** [comment]
Hey,

I'm running NC 24 on Univention appliance.
I was following this tutorial, how to recompile the imagemagick for HEIF/HEIC support: https://eplt.medium.com/5-minutes-to-install-imagemagick-with-heic-support-on-ubuntu-18-04-digitalocean-fe2d09dcef1


I managed to install imagemagick.
```
php -r 'phpinfo();' | grep HEIC
```

```
ImageMagick supported formats => 3FR, 3G2, 3GP, A, AAI, AI, ART, ARW, AVI, AVS, B, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, C, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DJVU, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FLV, FRACTAL, FTP, FTS, G, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, HALD, HDR, HEIC,...
```

So HEIC support is there. But for some reason I stll can not see the heif/heic files in my browser, nor see any heif thumbnails.

I tried to add the preview support lines into the config.php, but nothing, even after a full system restart.

I'm out of ideas. What did I misse Thanks in advance!

**Comment by blizzz** [comment]
`OC\Preview\HEIC` needs to be added to `enabledPreviewProviders` in config.php (check config.sample.php). Did you do that?

**Comment by Byter3** [comment]
> `OC\Preview\HEIC` needs to be added to `enabledPreviewProviders` in config.php (check config.sample.php). Did you do that?

Yes. But I gave up on it. Switched to AIO. It also gets updates much quicker.
