### ISSUE TITLE
The PHP OPcache module is not properly configured.

### ISSUE THREAD

**Issue by Fuseteam** [nextcloud/univention-app#176]
i noticed this warning in nextcloud
The PHP OPcache module is not properly configured. See the [documentation ↗](https://docs.nextcloud.com/server/24/admin_manual/installation/server_tuning.html#enable-php-opcache) for more information.
        The OPcache interned strings buffer is nearly full. To assure that repeating strings can be effectively cached, it is recommended to apply opcache.interned_strings_buffer to your PHP configuration with a value higher than 8.
       
please advise how we should bump this value, is it same to just shell in and configure it manually?

**Comment by JuiceofJam** [comment]
I manually added the following lines to:

/etc/php/7.4/apaches2/conf.d/10-opcache.conf

opcache.interned_strings_buffer=16
opcache.memory_consumption=64
