### ISSUE TITLE
occ is not executeable

### ISSUE THREAD

**Issue by sharky009** [nextcloud/univention-app#184]
The file /var/www/html/occ is not executeable. This has the consequence that collabora (and possible other) join script's can't run successfull. That's because they running the file without php prefixed.

The lines to check this are:
103: univention-app shell nextcloud sudo -u www-data /var/www/html/occ app:enable richdocuments
106: univention-app shell nextcloud sudo -u www-data /var/www/html/occ config:app:set richdocuments wopi_url --value="https://$FQDN/"
in /usr/lib/univention-install/50collabora.inst

This can be simply fixed if nextcloud sets a chmod +x on the occ file.

**Comment by blizzz** [comment]
https://github.com/nextcloud/univention-app/releases/tag/25.0.8-0

The scripts were all updated: https://github.com/nextcloud/univention-app/commit/359f031c08ca47d894b44b67b033c87edb066a3b

I am not aware we missed something, did we?

**Comment by blizzz** [comment]
Okay, it's collabora's script…

Yeah, not default behaviour, was bad to have it made executable in first place, back in the day
