### ISSUE TITLE
Update to Nextcloud 26/27

### ISSUE THREAD

**Issue by LightTemplar** [nextcloud/univention-app#188]
Nextcloud 25 has reached the EoL: https://help.nextcloud.com/t/nc-27-1-3-26-0-8-25-0-13-final/173005
Could you please update it the next major version?

**Comment by blizzz** [comment]
This will be a next step, yes.

**Comment by idominiki** [comment]
Any ETA for the UCS Update?

**Comment by joshtrichards** [comment]
NC26 - done: https://github.com/nextcloud/univention-app/releases/tag/26.0.10-0

**Comment by juliusknorr** [comment]
27 is also released
