### ISSUE TITLE
Enable HTTP Strict Transport Security

### ISSUE THREAD

**Issue by sixshooterz** [nextcloud/univention-app#56]
On the Security and Setup Warnings section, the following is displayed:
`The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the security tips.`

The fix is at this site:
https://docs.nextcloud.com/server/13/admin_manual/configuration_server/harden_server.html#use-https

I'm not sure which config file I need to add this to (the Docker container or the UCS server itself):
```
<VirtualHost *:443>
  ServerName cloud.nextcloud.com
    <IfModule mod_headers.c>
      Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
    </IfModule>
 </VirtualHost>
```

**Comment by sixshooterz** [comment]
Nevermind.

It goes at the bottom of
`/etc/apache2/sites-enabled/default-ssl.conf`

just below the Nextcloud docker ProxyPass lines.

Hope this helps anyone who needs it because they're OCD about warnings, informational or otherwise.

**Comment by blizzz** [comment]
Yes, this needs to be configured on the host, we cannot control it with the app.

**Comment by Fuseteam** [comment]
for those who are confused when it disappears from `/etc/apache2/sites-enabled/default-ssl.conf`
this can be configured with ucr with the following commands
```
ucr set apache2/hsts=yes
ucr set apache2/hsts/max-age=15552000
ucr set apache2/hsts/includeSubDomains=yes
```
