### ISSUE TITLE
Changes in LDAP are not reflected on the nextcloud side

### ISSUE THREAD

**Issue by fridok** [nextcloud/univention-app#57]
1) Changing the name of a group (or a user) in univention management console UI (UMC) does not change its name in nextcloud. When sharing a folder in nextcloud with this group or user you still have to use its old name or it will not be found.

2) Deleting a user in UMC that shared a folder in nextcloud with a group (without beforehand removing the share or deleting the folder) leads to the folder still being shown in every group member's nextcloud account. There you cannot open or remove the folder. It is an orphan folder ever to exist in the system.

3) This orphan folder eventually causes Nextcloud to stop synching at all.

See also: http://forge.univention.org/bugzilla/show_bug.cgi?id=47178

**Comment by blizzz** [comment]
1. By default, Nextcloud caches information for 10minutes. Then, you should get fresh information from LDAP.

2/3. would be a Nextcloud server issue. I heard another rumour recently, and will look into it.

**Comment by blizzz** [comment]
We had also some fixes in the server since. I think this is solved, otherwise shout out.
