### ISSUE TITLE
rework needed for LDAP bind user

### ISSUE THREAD

**Issue by dirkahrnke** [nextcloud/univention-app#6]
from http://forum.univention.de/viewtopic.php?t=6521&p=25170#p25170

Using a machine account to bind to LDAP needs a method to deal with password changes (see http://docs.software-univention.de/developer-reference-4.1.html#join:secret:change)

Another method is to create a dedicated bind user for the application.

**Comment by MiGrandjean** [comment]
Just to emphasize this: The current usage of the machine account to bind to LDAP breaks every Nextcloud installation after 21 days (default interval for renewing the password of the machine account) at the latest!

**Comment by blizzz** [comment]
Suggested fix in https://github.com/nextcloud/univention-app/pull/10
