### ISSUE TITLE
Manual Nextcloud config is lost after app update

### ISSUE THREAD

**Issue by va1entin** [nextcloud/univention-app#60]
I manually configured the `'defaultapp'` parameter inside the container at `/var/www/html/config/config.php`. Then I updated the app from 13.0.4 to 13.0.5 (UCS 4.3-1).
After the update, the config at `/var/www/html/config/config.php` was replaced with `/var/lib/univention-appcenter/apps/nextcloud/conf/config/config.php`. The `'defaultapp'` I had configured earlier was lost. So I suppose the config `/var/www/html/config/config.php` wasn't copied to  `/var/lib/univention-appcenter/apps/nextcloud/conf/config/config.php`, which would be the expected behaviour, I believe?

So the workflow to configure something manually for the app and update the app would be as follows:
- Install an editor inside the container
- Change `/var/www/html/config/config.php` inside the container to have the config applied immediately
- Change `/var/lib/univention-appcenter/apps/nextcloud/conf/config/config.php` so the config survives app updates
- Update app

I think it might be a good idea to just mount  `/var/lib/univention-appcenter/apps/nextcloud/conf/config/` at `/var/www/html/config` inside the container. That way the app wouldn't even have to copy the config around because it would be stored safely on the host and mounted to the desired place.

**Comment by blizzz** [comment]
This is unexpected indeed. The store_data script copies the config file to the permanent directory, and restore_data before backup copies it back.

**Comment by va1entin** [comment]
I think I found the issue. See #62

**Comment by blizzz** [comment]
Fixed with #62, thx @va1entin
