### ISSUE TITLE
Add automatic security updates to the docker image

### ISSUE THREAD

**Issue by MiGrandjean** [nextcloud/univention-app#7]
As of today, the underlying Ubuntu 16.04 of the docker image is missing a couple of package updates right after installation (e.g. PHP from 7.0.13 to 7.0.15 and some libs). All of those are categorized as security updates, but there is no mechanism to automatically apply Ubuntu packge updates inside the nextcloud docker app.

If this makes sense at all depends on how often the App itself is updated with a new (up-to-date) docker image. Currently I would opt for adding automatic security updates to the docker image to be safe between App/Image updates.

I guess one needs to combine the "Upgrade within the container" section from http://wiki.univention.de/index.php?title=Docker_Apps/Container_Scripts and something like the `unattended-upgrades` package from Ubuntu: https://help.ubuntu.com/lts/serverguide/automatic-updates.html

**Comment by oparoz** [comment]
Is this the right way @LukasReschke @blizzz ?

**Comment by blizzz** [comment]
We've got ``unattended-upgrades`` installed which should look for and apply security updates once a day https://github.com/nextcloud/univention-app/blob/master/Dockerfile#L49

**Comment by MiGrandjean** [comment]
My bad, @blizzz is right. I missed that line in the Dockerfile. Additionally, both of my test machines never updated themselves because they were always paused/suspended when `cron.daily` should have started the unattended upgrade. 

Sorry for the inconvenience, I'm going to close this issue because it's **INVALID**.
