### ISSUE TITLE
Use LDAPS connection in Nextcloud per default

### ISSUE THREAD

**Issue by ngulden** [nextcloud/univention-app#73]
I should be thought about changing the LDAP configuration to use LDAPS per default. See https://help.univention.com/t/nextcloud-ldaps/10370 on how this can be done for the moment.

Maybe a documentation is already sufficient enough. I heard such request only one time.

**Comment by blizzz** [comment]
Another option using standardized StartTLS, which essentially means setting the `ldapTLS` flag to 1. On a short test it worked out fine, right after setting this to one.

Do you have best practices or recommendations which one to use? At least from the standardization PoV, StartTLS is recommended, using LDAPS does work and avoids previous plain text connections.

**Comment by ngulden** [comment]
There has been a solution at Univention Help: https://help.univention.com/t/nextcloud-ldaps/10370/7.

**Comment by blizzz** [comment]
Mh, i'd rather set the CA in the ldap.conf, if possible, than turning of the SSL verification.  

Well, if there is no preference between LDAPS and StartTLS I'd just use the later.

**Comment by blizzz** [comment]
@ngulden 

> Mh, i'd rather set the CA in the ldap.conf, if possible, than turning of the SSL verification.

UCS takes care about upgrading the certificate files. Could it also set the TLS_CACERT to the proper certificate in the ldap.conf, just as it is already on the host?

**Comment by blizzz** [comment]
As discussed, we set the config initially in the container and go for  StartTLS.
