### ISSUE TITLE
configure mail server

### ISSUE THREAD

**Issue by blizzz** [nextcloud/univention-app#77]
since Nc 14 the build-in PHP mailer is not supported anymore. With default settings, there is a bug showing a confusing error message to end users: https://github.com/nextcloud/server/issues/12597

→ The mail server should be configured properly, c.f. https://wiki.univention.de/index.php/Integration_with_UCS/Mail

fyi @ngulden

**Comment by blizzz** [comment]
The wiki-link however does not reveal how to get relevant information (port, transport encryption, whether authentication is needed, and which (nop-reply) email can be used or created).

**Comment by ngulden** [comment]
The wiki gives best practice recommendations for SMTP:

* port: 587
* encryption: TLS
* Auth login or Auth Plain

**Comment by blizzz** [comment]
@ngulden yes, but it there a way to figure out what is effectively configured? For auth, can we use the same credentials of the LDAP service user?

**Comment by dwiesent** [comment]
@blizzz The recommendations are for "proper" mail delivery. You would also need a real user with a mailPrimaryAddress configured (so the machine account does not work). But I guess you need this for "system messages" much like cron does it in certain jobs.
In this case, you would only need to access port 25. Any "from address" is accepted. Be aware that those mails will likely not be delivered to "outside addresses", though.
You could use a configurable address (see https://docs.software-univention.de/app-provider-4.3.html#app-settings) or use "nextcloud@$fqdn".
You should still search for a real mail server. Postfix is installed on all UCS servers (i.e., also on the Docker Host) but I would not assume that forwarding is correctly configured.

**Comment by blizzz** [comment]
Mh, all in all, I tend to leave it like this and just add "Please configure the mail server (if you have not done already)" to some Install and update readme. As figuring out the config seems to be vague, plus I consider this a killer:

> he recommendations are for "proper" mail delivery. You would also need a real user with a mailPrimaryAddress configured (so the machine account does not work).

**Comment by blizzz** [comment]
as discussed with @ngulden it is not possible to certainly figure out for UCS which mailing system (internal or external) is used, therefore deriving any reliable information about the mail setup is not possible → closing
