### ISSUE TITLE
Nextcloud updates remove additional installed apps

### ISSUE THREAD

**Issue by ngulden** [nextcloud/univention-app#84]
When a Nextcloud installation in UCS App Center is updated to the next version, additionally installed plugins/apps are not present anymore, like for example the apps "Bookmarks" and "Passman" including their data. See https://help.univention.com/t/nextcloud-upgrade-removes-apps-like-bookmarks-and-passman/11010

Aren't plugins/apps not stored in a specific subfolder in the container? Wouldn't be a good possibility to configure it as volume and make the apps and their data persistent? Are there any side effects on this?

**Comment by blizzz** [comment]
Would be a regression. The apps were installed from the appserver again. Changed configuration and an additional permanent app folder would be the alternative, and more robust indeed.

**Comment by fridok** [comment]
At our Nextcloud  installation in UCS the calendar app is disabled after every update. Very annoying. We are at NC 14.

**Comment by blizzz** [comment]
It's fixed with 14.0.8 which should hit the appcenter soon, publishing was requested.
