### ISSUE TITLE
Review disabling of updatechecker

### ISSUE THREAD

**Issue by MiGrandjean** [nextcloud/univention-app#9]
The `README.md` says that the updatechecker is disabled and updates are provided via Univention App Center. Unfortunately, this doesn't seem to work. An Update of Nextcloud from 11.0.1 to 11.0.2 can be initiated via the Nextcloud webinterface (https://FQDN/nextcloud/index.php/settings/admin → Server settings). 

I am aware of [this line here](https://github.com/nextcloud/univention-app/blob/master/setup.sh#L87), but this doesn't seem to be sufficient.

See also the corresponding entry in the [Univention Forum](http://forum.univention.de/viewtopic.php?f=67&t=6574) (german)

**Comment by blizzz** [comment]
Apparently updatenotification app needs to be disabled.
