### ISSUE TITLE
Pre-configure Single Sign-On with SAML in the Nextcloud App

### ISSUE THREAD

**Issue by ngulden** [nextcloud/univention-app#91]
UCS and Nextcloud support SAML. [This blog article](https://www.univention.com/blog-en/2019/02/how-to-single-sign-on-for-nextcloud/) describes how SAML can be setup manually. The blog posting describes where the needed information like URLs and certificates can be found. This information needs to be obtained during the app configuration and provided to the respective sides. I guess, the join script is the best place for those tasks.

In the context of this issue, the app should prepare all necessary settings in Nextcloud and the UCS host to setup the SAML configuration. It consists of the steps for Nextcloud as *"Service Provider"* and UCS as *"Identity Provider"*.

The setup should allow both, classic LDAP authentication via the Nextcloud login form and single sign-on via the respective login form on UCS as identity provider.

**Comment by blizzz** [comment]
done in 16.0.4-0
