### ISSUE TITLE
Identifie users by their entryUUID

### ISSUE THREAD

**Issue by smidt** [nextcloud/univention-app#92]
Changing the user name in UCS leads to a new user in Nextcloud. It would be better if Nextcloud identified the users by their entryUUID. The entryUUID never changes and is retained when the user is moved or the user name is changed.

**Comment by blizzz** [comment]
@smidt the entryUUID is actually being used (default value) as it is not overridden to something else: https://github.com/nextcloud/univention-app/blob/master/inst#L185

Either this setting was changed manually, or a new entry was created on the directory.

**Comment by blizzz** [comment]
I'm closing this for now, we can always reopen if there are more questions or information needed for example.

**Comment by smidt** [comment]
Hi @blizzz, I'd like to reopen the issue because a value which you mentioned is not set in the line.
The default within Nextcloud is uid which I think makes sense if you want to connect to any LDAP you don't know anything further about. The line also shows a possibility that you could implement this very easily but it just hasn't happened yet. 
I would recommend to set entryUUID there. We do that in comparable scenarios. 
`data+="&configData[ldapExpertUUIDUserAttr]=entryUUID"`
Should I try to submit this as PR?

**Comment by blizzz** [comment]
>  data+="&configData[ldapExpertUUIDUserAttr]=entryUUID"

this is autodetected, therefore I have not set it manually. But we can absolutely do that. You're PR is welcome!

**Comment by smidt** [comment]
Hi @blizzz,
I'm sorry for the effort but when testing my patch I noticed that user renaming actually works out-of-the-box. I think I originally tested this with a too old(?) Nextcloud version. I think then I close the issue again.
Cheers,
Michel
