### ISSUE TITLE
gmp library missing

### ISSUE THREAD

**Issue by kevindkorte** [nextcloud/univention-app#99]
Multiple Nextcloud Apps are using the gmp library. However, it is not installed within the docker image and no information is provided on how to install it.

Steps to reproduce:
* Install UCS
* Install NextCloud from the AppCenter
* Try to enable for example Bookmarks

**Comment by blizzz** [comment]
@kevindkorte  mind adding in https://github.com/nextcloud/univention-app/blob/master/Dockerfile#L37-L63 and open a pull request?

**Comment by kevindkorte** [comment]
pull request is waiting

**Comment by blizzz** [comment]
fixed with #100, will ship with next  upgrade
